# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d71996b2450760e9279104b32952ee5c0ea08c0a6a616f55c4e9c477ed21d48351acea979ea988f4d36c06c96aba0b472035af238b09b11e52dc598327eeeb8

test:
  secret_key_base: 232ec824a6bd64bb8e60b689b7c6cb5fa4a56f3252a946f7959735c64af5de1a2e6aad64b3de7f8e284dfa824746827fa6990bb00e084af713f1f8d2967f1b22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
